#!/bin/env python3
import sys
from benchgo import BENCHGO_VERSION, ROOT_HELP, TRINO_HELP, SPARKDF_HELP, SQPARKSQL_HELP, DREMIO_HELP, VASTDBSDK_HELP

if __name__ == "__main__":

    if len(sys.argv) > 1 and sys.argv[1] == '--version':
        print("benchgo version: {}".format(BENCHGO_VERSION))
        sys.exit(0)

    if len(sys.argv) < 2:
        sys.stderr.write(ROOT_HELP)
        sys.exit(1)

    elif sys.argv[1] == 'trino':

        if sys.argv[2] == 'tpcds':
            from benchgo.trino.tpcds import TrinoTPCDS
            TrinoTPCDS().run()
            
        elif sys.argv[2] == 'tpch':
            from benchgo.trino.tpch import run
            run()
            
        elif sys.argv[2] == 'transaction':
            from benchgo.trino.transaction import run
            run()
            
        elif sys.argv[2] == 'throughput':
            from benchgo.trino.throughput import run
            run()

        else:
            sys.stderr.write(TRINO_HELP)

    elif sys.argv[1] == 'sparksql':

        if sys.argv[2] == 'tpcds':
            from benchgo.sparksql.tpcds import run
            run()
            
        elif sys.argv[2] == 'tpch':
            from benchgo.sparksql.tpch import run
            run()
            
        elif sys.argv[2] == 'transaction':
            from benchgo.sparksql.transaction import run
            run()
            
        elif sys.argv[2] == 'throughput':
            from benchgo.sparksql.throughput import run
            run()

        else:
            sys.stderr.write(SQPARKSQL_HELP)

    elif sys.argv[1] == 'sparkdf':
            
        if sys.argv[2] == 'transaction':
            from benchgo.sparksql.transaction import run
            run()
            
        elif sys.argv[2] == 'throughput':
            from benchgo.sparksql.throughput import run
            run()

        else:
            sys.stderr.write(SPARKDF_HELP)

    elif sys.argv[1] == 'dremio':

        if sys.argv[2] == 'tpcds':
            from benchgo.dremio.tpcds import run
            run()
            
        elif sys.argv[2] == 'tpch':
            from benchgo.dremio.tpch import run
            run()
            
        elif sys.argv[2] == 'throughput':
            from benchgo.dremio.throughput import run
            run()

        else:
            sys.stderr.write(DREMIO_HELP)

    elif sys.argv[1] == 'vastdbsdk':
            
        if sys.argv[2] == 'transaction':
            from benchgo.vastdbsdk.transaction import run
            run()
            
        elif sys.argv[2] == 'throughput':
            from benchgo.vastdbsdk.throughput import run
            run()
        
        else:
            sys.stderr.write(VASTDBSDK_HELP)

    elif sys.argv[1] == 'gen-spark-config':

        from benchgo.spark_config_template import *
        import os
        try:
            os.mkdir(BENCHGO_CONF_HOME)
            with open(CONFIG_OUT_LOCATION, "x") as fh:
                fh.write(CONFIG_TEMPLATE)
            print("template written to {}, you need to configure it".format(CONFIG_OUT_LOCATION))
        except FileExistsError:
            print("'{}' already exists, move or remove and try again".format(CONFIG_OUT_LOCATION))
    
    else:
        sys.stderr.write(ROOT_HELP)
        sys.exit(1)